name: E2E tests

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      group: eds-runners
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Start containers
        run: docker compose up --force-recreate -d --quiet-pull
      - name: Show Kafka output
        run: docker logs eds-init-kafka-1
      - name: Run tests
        env:
          SM_SNOWFLAKE_PASSWORD: ${{ secrets.SM_SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_SECRET_ACCESS_KEY: ${{ secrets.SNOWFLAKE_SECRET_ACCESS_KEY }}
          GCS_ACCESS_KEY_ID: ${{ secrets.GCS_ACCESS_KEY_ID }}
          GCS_SECRET_ACCESS_KEY: ${{ secrets.GCS_SECRET_ACCESS_KEY }}
          GCS_TEST_BUCKET: ${{ vars.GCS_TEST_BUCKET }}
        run: make e2e
      - name: Stop containers
        run: docker compose down
        if: always()
